# fusilliprovider
[components.dbg."iree-libs/fusilliprovider/stage"]
[components.lib."iree-libs/fusilliprovider/stage"]
exclude = [
  "lib/*.a",
]
[components.test."iree-libs/fusilliprovider/stage"]
include = [
  "bin/fusilli_plugin_*_test",
  "bin/fusilli_plugin_test_infra/*",
]
