# rocjpeg
[components.dbg."media-libs/rocjpeg/stage"]
[components.dev."media-libs/rocjpeg/stage"]
[components.lib."media-libs/rocjpeg/stage"]
[components.test."media-libs/rocjpeg/stage"]
include = [
  "share/rocjpeg/**",
]
