name: Publish no_rocm_image_ubuntu24_04_ocl_rt images
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'stage/docker/**'
    paths:
      - dockerfiles/no_rocm_image_ubuntu24_04_ocl_rt.Dockerfile
      - .github/workflows/publish_no_rocm_image_ubuntu24_04_ocl_rt.yml

permissions:
  contents: read
  packages: write

jobs:
  publish_no_rocm_image_ubuntu24_04_ocl_rt:
    uses: ./.github/workflows/publish_dockerfile.yml
    with:
      DOCKER_FILE_NAME: no_rocm_image_ubuntu24_04_ocl_rt
      DOCKER_IMAGE_NAME: no_rocm_image_ubuntu24_04_ocl_rt
